config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'video_games#welcome'

  resources :users, only: [:new, :create, :show] do
    resources :collection_video_games
  end

  resources :video_games do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :collection_video_games
  has_many :video_games, through: :collection_video_games

  validates :collection_type, presence: true, inclusion: { in: %w[Completed In-Progress Wishlist] }
end

app/models/collection_video_game.rb
class CollectionVideoGame < ApplicationRecord
  belongs_to :collection
  belongs_to :video_game

  validates :collection_id, presence: true
  validates :video_game_id, presence: true
  validates :playtime, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :video_game

  validates :title, presence: true
  validates :body, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :collections
  has_many :reviews
  has_many :video_games, through: :collections
  has_many :reviewed_video_games, through: :reviews, source: :video_game

  validates :username, presence: true, uniqueness: true
  validates :bio, presence: true
  validates :password, presence: true, confirmation: true
  validates :password_confirmation, presence: true

  def collection_by_type(collection_type)
    return unless collections.where(collection_type: collection_type).any?

    collection = collections.where(collection_type: collection_type)
    collection.first.video_games
  end

  def reviewed_video_game?(video_game_id)
    video_game = VideoGame.find(video_game_id)
    reviewed_video_games.include?(video_game)
  end
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
  has_many :reviews
  has_many :collection_video_games
  has_many :collections, through: :collection_video_games

  validates :name, presence: true
  validates :description, presence: true
  validates :release_date, presence: true
  validates :developer, presence: true
  validates :publisher, presence: true
  validates :platform, presence: true

  def average_rating
    average = Review.where(video_game_id: id).average(:rating)
    average.nil? ? 0 : average.round(2)
  end

  scope :top_rated, -> {
    joins(:reviews)
      .select("video_games.*, AVG(reviews.rating) AS average_rating")
      .group("video_games.id")
      .order("average_rating DESC")
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate_user
    return if current_user

    redirect_to login_path, alert: "Please log in to continue"
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/collection_video_games_controller.rb
class CollectionVideoGamesController < ApplicationController
  before_action :authenticate_user
  before_action :set_user

  def new
    @collection_video_game = CollectionVideoGame.new
    @video_game = VideoGame.new
    @video_games = VideoGame.all
  end

  def create
    @video_game = find_or_create_video_game

    @collection = Collection.find_or_create_by(user_id: @user.id,
                                               collection_type: collection_video_game_params[:collection_type])
    @collection_video_game = @collection.collection_video_games.build(video_game: @video_game,
                                                                      playtime: collection_video_game_params[:playtime])
    if @collection_video_game.save
      redirect_to user_path(@user), notice: "Video game added to collection."
    else
      @video_games = VideoGame.all
      render :new
    end
  end

private

  def collection_video_game_params
    params.require(:collection_video_game).permit(:playtime, :collection_type, :video_game_id)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def find_or_create_video_game
    if collection_video_game_params[:video_game_id].present?
      VideoGame.find(collection_video_game_params[:video_game_id])
    else
      video_game = VideoGame.new(video_game_params)
      video_game.save ? video_game : nil
    end
  end

  def video_game_params
    params.require(:video_game).permit(:name, :description, :release_date, :developer, :publisher, :platform)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_video_game
  before_action :authenticate_user
  def new
    @review = Review.new
  end

  def create
    @review = @video_game.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to @video_game, notice: "Review was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @review = current_user.reviews.find_by(id: params[:id])
    redirect_to(video_game_path(@video_game)) if @review.blank?
  end

  def update
    @review = current_user.reviews.find_by(id: params[:id])
    @review.update(review_params)

    if @review.save
      redirect_to @video_game, notice: "Review was updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

private

  def set_video_game
    @video_game = VideoGame.find(params[:video_game_id])
  end

  def review_params
    params.require(:review).permit(:title, :body, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully."
    else
      flash.now[:alert] = "Invalid username or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out successfully."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @completed_games = @user.collection_by_type("Completed")
    @in_progress_games = @user.collection_by_type("In-Progress")
    @wishlist_games = @user.collection_by_type("Wishlist")
  end

private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :bio)
  end
end

app/controllers/video_games_controller.rb
class VideoGamesController < ApplicationController
  before_action :authenticate_user

  def welcome
    @top_rated_video_games = VideoGame.top_rated.limit(3)
  end

  def index
    @video_games = VideoGame.top_rated
  end

  def show
    @video_game = VideoGame.find(params[:id])
    @user = User.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collection_video_games/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Add Video Game to Collection</h1>

  <%= form_with(model: [@user, @collection_video_game], url: user_collection_video_games_path(@user), method: :post, local: true, data: { turbo: false }, class: "p-4 border rounded shadow-sm") do |form| %>
    <%= render 'layouts/form_errors', model: @collection_video_game %>
    <div class="form-group mb-3">
      <%= form.label :collection_type, "Collection Type", class: "form-label" %>
      <%= form.select :collection_type, options_for_select(['Completed', 'In-Progress', 'Wishlist']), { include_blank: "Select collection" }, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :playtime, class: "form-label" %>
      <%= form.text_field :playtime, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :video_game_id, "Select Existing Video Game", class: "form-label" %>
      <%= form.collection_select :video_game_id, @video_games, :id, :name, { include_blank: "Select a Video Game" }, { class: "form-control" } %>
    </div>

    <h4 class="mt-4 mb-3">Or Add a New Video Game</h4>

    <div class="border p-3 rounded bg-light mb-4">
      <%= fields_for :video_game, @collection_video_game.build_video_game do |vg_form| %>
        <div class="form-group mb-3">
          <%= vg_form.label :name, class: "form-label" %>
          <%= vg_form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= vg_form.label :description, class: "form-label" %>
          <%= vg_form.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= vg_form.label :release_date, class: "form-label" %>
          <%= vg_form.text_field :release_date, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= vg_form.label :developer, class: "form-label" %>
          <%= vg_form.text_field :developer, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= vg_form.label :publisher, class: "form-label" %>
          <%= vg_form.text_field :publisher, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <%= vg_form.label :platform, class: "form-label" %>
          <%= vg_form.text_field :platform, class: "form-control" %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.submit 'Add to Collection', class: 'btn btn-primary w-100' %>
    </div>
  <% end %>
</div>

app/views/layouts/_form_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(model.errors.count, "error") %> prohibited this <% model %> from being saved:</h4>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Video Game Archive</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Video Games", video_games_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
      </li>
    </ul>
  </div>
  <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoGameBacklogManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "rails-ujs" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless controller_name == 'sessions' && (action_name == 'new' || action_name == 'create') || controller_name == 'users' && (action_name == 'new' || action_name == 'create' )%>
      <%= render 'layouts/navbar' %>
    <% end %>

    <% flash.each do |key, message| %>
      <div class="flash flash-<%= key %>">
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: [@video_game, @review], local: true, class: "p-4 border rounded shadow-sm") do |form| %>
  <%= render 'layouts/form_errors', model: @review %>

  <div class="form-group mb-3">
    <%= form.label :title, "Review Title", class: "form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Enter your review title", value: @review.title %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :body, "Review Body", class: "form-label" %>
    <%= form.text_area :body, class: "form-control", placeholder: "Write your review here", rows: 5, value: @review.body %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :rating, "Rating", class: "form-label" %>
    <%= form.number_field :rating, class: "form-control", step: 0.1, min: 0, max: 5, placeholder: "Rate from 0 to 5", value: @review.rating %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit "Submit Review", class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form" %>

app/views/reviews/new.html.erb
<h1>Write a Review</h1>

<%= render "form" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, local: true, data: { turbo: false } do |form| %>
  <%= render 'layouts/form_errors', model: @user %>


  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header text-center">
          <h1><%= @user.username %></h1>
        </div>
        <div class="card-body">
          <h3 class="text-center text-muted"><%= @user.bio %></h3>

          <hr>

          <% if @user.id == session[:user_id]%>
            <%= link_to "Add to collections", new_user_collection_video_game_path(@user), class: "btn btn-primary" %>
          <% end%>

          <h4 class="mt-4">Completed</h4>
          <ul class="list-group">
            <% if @completed_games %>
              <% @completed_games.each do |video_game| %>
                <li class="list-group-item">
                  <%= link_to video_game.name, video_game_path(video_game) %>
                </li>
              <% end %>
            <% end %>
          </ul>

          <h4 class="mt-4">In-Progress</h4>
          <ul class="list-group">
            <% if @in_progress_games %>
              <% @in_progress_games.each do |video_game| %>
                <li class="list-group-item">
                  <%= link_to video_game.name, video_game_path(video_game) %>
                </li>
              <% end %>
            <% end %>
          </ul>

          <h4 class="mt-4">Wishlist</h4>
          <ul class="list-group">
            <% if @wishlist_games %>
              <% @wishlist_games.each do |video_game| %>
                <li class="list-group-item">
                  <%= link_to video_game.name, video_game_path(video_game) %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/video_games/index.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">All Video Games</h1>
  <div class="list-group m-4">
    <% @video_games.each do |video_game| %>
      <a href="<%= video_game_path(video_game) %>" class="list-group-item list-group-item-action p-3">
        <h4 class="mb-1"><%= video_game.name %></h4>
        <% if video_game.reviews.any? %>
          <p class="mb-1">Rating: <%= video_game.average_rating %></p>
        <% else %>
          <p class="mb-1 text-muted">No reviews yet</p>
        <% end %>
      </a>
    <% end %>
  </div>
</div>

app/views/video_games/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title"><%= @video_game.name %></h1>
      <h3 class="card-subtitle mb-3 text-muted"><%= @video_game.description %></h3>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Release Date:</strong> <%= @video_game.release_date %></li>
        <li class="list-group-item"><strong>Developer:</strong> <%= @video_game.developer %></li>
        <li class="list-group-item"><strong>Publisher:</strong> <%= @video_game.publisher %></li>
        <li class="list-group-item"><strong>Platform:</strong> <%= @video_game.platform %></li>
      </ul>
    </div>
  </div>
  <div class="mt-5">
    <h2>Reviews</h2>
    <% unless @user.reviewed_video_game?(params[:id]) %>
      <%= link_to "Add Review", new_video_game_review_path(@video_game), class: "btn btn-primary" %>
    <% end %>
    <% if @video_game.reviews.any? %>
      <div class="list-group">
        <% @video_game.reviews.each do |review| %>
          <div class="list-group-item">
            <h4 class="mb-1"><%= review.title %></h4>
            <p class="mb-1"><%= review.body %></p>
            <small class="text-muted">Rating: <%= review.rating %> | Reviewed by <%= link_to review.user.username, user_path(review.user) %></small>
            <% if @user.id == review.user.id %>
              <%= link_to "Edit Review", edit_video_game_review_path(@video_game, review), class: "btn btn-primary" %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <p> No reviews yet. </p>
    <% end %>
  </div>
</div>

app/views/video_games/welcome.html.erb
<div class="container mt-5">
  <header class="text-center">
    <h1 class="display-4">Welcome to the Video Game Archive</h1>
    <p class="lead">The ultimate app to manage your video game backlog</p>
  </header>

  <section class="my-5">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h2 class="text-center">What We Do</h2>
        <p class="text-center">Our app helps you organize and track all the games you own. Add games to your backlog, mark them as completed, track your playtime, review them, and more! With the Video Game Archive, your gaming progress is always in check.</p>
      </div>
    </div>
  </section>

  <section class="my-5">
    <h2 class="text-center">Top Rated Games</h2>
      <%= render(TopRatedGamesComponent.new(games: @top_rated_video_games)) %>
  </section>
</div>